# Nama workflow yang akan muncul di tab "Actions" GitHub
name: Build & Release DM POS

# Pemicu: Workflow ini hanya akan berjalan saat ada tag baru (misal: v1.5.7) di-push
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  # Nama pekerjaan, bisa apa saja
  release:
    # Menggunakan mesin virtual Windows terbaru untuk membuat file .exe
    runs-on: windows-latest

    steps:
      # Langkah 1: Mengunduh kode dari repository Anda ke mesin virtual
      - name: Check out Git repository
        uses: actions/checkout@v4

      # Langkah 2: Menyiapkan lingkungan Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          # PERBAIKAN: Menggunakan Node.js versi 20 yang dibutuhkan oleh Vite
          node-version: '20'
          cache: 'npm'      # Mengaktifkan cache untuk mempercepat instalasi

      # Langkah 3: Menginstal semua dependencies dari package.json
      - name: Install dependencies
        run: npm install

      # Langkah 4: Menjalankan script build dan rilis
      - name: Build and release application
        # Menggunakan script "dist" atau "build:electron" dari package.json
        run: npm run dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

